site_name: "wysocki.io"
site_url: https://www.wysocki.io/
site_author: Tyler Wysocki
site_description: >-
  Tyler Wysocki's Portfolio: LeetCode problem solutions, projects, and more.

########### Repository ##########
repo_name: tywysocki/leetcode-solutions
repo_url: https://github.com/tywysocki/leetcode-solutions

########### Copyright ##########
copyright: >
  Copyright &copy; 2023 Tyler Wysocki -
  <a href="#__consent">Change cookie settings</a>

########### Configuration ##########
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  logo: assets/logo-final.png
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    tag:
      swift: simple/swift
      python: simple/python
      python3: simple/python
      easy: fontawesome/solid/cake-candles
      medium: fontawesome/solid/handshake
      hard: fontawesome/solid/skull

########## Plugins ##########
plugins:
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - tags:
      tags_file: 'tags.md'
  - social:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

####### Additional configuration #######
extra:
  tags:
    Swift: swift
    Python: python
    Python3: python3
    Easy: easy
    Medium: medium
    Hard: hard
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tywysocki
    - icon: simple/leetcode
      link: https://leetcode.com/tywysocki


####### Custom CSS #######
extra_css:
  - stylesheets/extra.css

####### Custom JavaScript #######
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js

####### Extensions #######
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - toc
  - footnotes
  - md_in_html
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: false
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: tywysocki
      repo: leetcode-solutions
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details

########## Navigation ##########
nav:
  - Home: README.md
  - LeetCode: 
      - 'solutions/README.md'
      - Two Sum: 'solutions/easy/two-sum.md'
      - Add Two Numbers: 'solutions/medium/add-two-numbers.md'
      - Longest Substring Without Repeating Characters: 'solutions/medium/longest-substring-without-repeating-characters.md'
      - Median of Two Sorted Arrays: 'solutions/hard/median-of-two-sorted-arrays.md'
      - Longest Longest Palindromic Substring: 'solutions/medium/longest-palindromic-substring.md'
      - Zigzag Conversation: 'solutions/medium/zigzag-conversation.md'
      - Reverse Integer: 'solutions/medium/reverse-integer.md'
      - String to Integer (atoi): 'solutions/medium/string-to-integer-atoi.md'
      - Palindrome Number: 'solutions/easy/palindrome-number.md'
      - Regular Expression Matching: 'solutions/hard/regular-expression-matching.md'
      - Container With Most Water: 'solutions/medium/container-with-most-water.md'
      - Integer to Roman: 'solutions/medium/integer-to-roman.md'
      - Roman to Integer: 'solutions/easy/roman-to-integer.md'
      - Merge k Sorted Lists: 'solutions/hard/merge-k-sorted-lists.md'
      - Reverse Nodes in k-Group: 'solutions/hard/reverse-nodes-in-k-group.md'
      - Remove Duplicates from Sorted Array: 'solutions/easy/remove-duplicates-from-sorted-array.md'
      - Substring With Concatenation of All Words: 'solutions/hard/substring-with-concatenation-of-all-words.md'
      - Longest Valid Parentheses: 'solutions/hard/longest-valid-parentheses.md'
      - Sudoku Solver: 'solutions/hard/sudoku-solver.md'
      - N-Queens 2: 'solutions/hard/n-queens-2.md'
      - Pascal's Triangle 2: 'solutions/easy/pascals-triangle-2.md'
      - Tenth Line: 'solutions/easy/tenth-line.md'
      - Integer Break: 'solutions/medium/integer-break.md'
      - Backspace String Compare: 'solutions/easy/backspace-string-compare.md'
      - Number of Ways to Stay in the Same Place After Some Steps: 'solutions/hard/number-of-ways-to-stay-in-the-same-place-after-some-steps.md'
      - Validate Binary Tree Nodes: 'solutions/medium/validate-binary-tree-nodes.md'
      - Constrained Subsequence Sum: solutions/hard/constrained-subsequence-sum-1425.md
      - Max Dot Product of Two Subsequences: 'solutions/hard/max-dot-product-of-two-subsequences.md'
      - Parallel Courses 3: 'solutions/hard/parallel-courses-3.md'
      - Tags: 'tags.md'
  - Portfolio:
      - 'portfolio/README.md'
      - OpenAI: 'portfolio/openai.md'
  - Blog: 
      - 'blog/index.md'