site_name: "wysocki.io"
site_url: https://www.wysocki.io/
site_author: Tyler Wysocki
site_description: >-
  LeetCode Solutions Portfolio

# Repository
repo_name: tywysocki/leetcode-solutions
repo_url: https://github.com/tywysocki/leetcode-solutions

# Copyright
copyright: >
  Copyright &copy; 2023 Tyler Wysocki -
  <a href="#__consent">Change cookie settings</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  logo: assets/logo-final.png

  # Icons
  icon:
    # Repo Icon
    repo: fontawesome/brands/github

    # Tag Icons
    tag:
      swift: simple/swift
      python: simple/python
      python3: simple/python
      easy: fontawesome/solid/cake-candles
      medium: fontawesome/solid/handshake
      hard: fontawesome/solid/skull

  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  # Tags
  - tags:
      tags_file: 'tags.md'

  # Social Cards
  - social:

  # Search Bar
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

  # Blog Posts: https://squidfunk.github.io/mkdocs-material/plugins/blog/#meta.date-custom-date
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/articles"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      # post_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # post_slugify_separator: _
      post_excerpt: optional
      post_excerpt_max_authors: 2
      post_excerpt_max_categories: 2
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      post_readtime_words_per_minute: 300
      archive: false
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "archive/{date}"
      archive_toc: true
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # categories_slugify_separator: _
      categories_allowed:
        - Easy
        - Medium
        - Hard
        - Swift
        - Python
        - Python3
        - String
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "~2~"
      pagination_if_single_page: false
      pagination_keep_content: false
      authors: true

# Additional configuration
extra:
  # Tag id: icon
  tags:
    Swift: swift
    Python: python
    Python3: python3
    Easy: easy
    Medium: medium
    Hard: hard

    # Cookies Message
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

  # Versioning
  version:
    default: stable
    provider: mike

  # Hide Generator
  generator: false
  annotate:
    json: [.s2]

  # Social Icons
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tywysocki
    - icon: simple/leetcode
      link: https://leetcode.com/tywysocki

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Custom JavaScript
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink:
      separator: "_"
  - footnotes
  - md_in_html
  - tables
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: tywysocki
      repo: leetcode-solutions
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde

# Page Tree
nav:
  - Home:
      - home/README.md
  - LeetCode Solutions:
      - solutions/README.md
      - Tags: 'tags.md'
      - Problem 1: 'solutions/easy/two-sum.md'
      - Problem 2: 'solutions/medium/add-two-numbers.md'
      - Problem 3: 'solutions/medium/longest-substring-without-repeating-characters.md'
      - Problem 4: 'solutions/hard/median-of-two-sorted-arrays.md'
      - Problem 5: 'solutions/medium/longest-palindromic-substring.md'
      - Problem 6: 'solutions/medium/zigzag-conversation.md'
      - Problem 7: 'solutions/medium/reverse-integer.md'
      - Problem 8: "solutions/medium/string-to-integer-atoi.md"
      - Problem 9: "solutions/easy/palindrome-number.md"
      - Problem 10: "solutions/hard/regular-expression-matching.md"
      - Problem 11: "solutions/medium/container-with-most-water.md"
      - Problem 12: solutions/medium/integer-to-roman.md
      - Problem 13: solutions/easy/roman-to-integer.md
      - Problem 23: solutions/hard/merge-k-sorted-lists.md
      - Problem 25: solutions/hard/reverse-nodes-in-k-group.md
      - Problem 26: solutions/easy/remove-duplicates-from-sorted-array.md
      - Problem 30: solutions/hard/substring-with-concatenation-of-all-words.md
      - Problem 32: solutions/hard/longest-valid-parentheses.md
      - Problem 37: solutions/hard/sudoku-solver.md
      - Problem 52: solutions/hard/n-queens-2.md
      - Problem 119: solutions/easy/pascals-triangle-2.md
      - Problem 195: solutions/easy/tenth-line.md
      - Problem 343: solutions/medium/integer-break.md
      - Problem 844: solutions/easy/backspace-string-compare.md
      - Problem 1269: solutions/hard/number-of-ways-to-stay-in-the-same-place-after-some-steps.md
      - Problem 1361: solutions/medium/validate-binary-tree-nodes.md
      - Problem 1458: solutions/hard/max-dot-product-of-two-subsequences.md
      - Problem 2050: solutions/hard/parallel-courses-3.md
  - Portfolio:
      - portfolio/README.md
      - portfolio/openai.md
  - Blog: "blog/index.md"