site_name: "LeetCode Solutions"
site_url: https://www.wysocki.io
site_author: Tyler Wysocki
site_description: >-
  LeetCode Solutions Portfolio. 

# Repository
repo_name: tywysocki/leetcode-solutions
repo_url: https://github.com/tywysocki/leetcode-solutions

# Copyright
copyright: Copyright &copy; 2023 Tyler Wysocki

# Configuration
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: assets/logo-final.png

  # Icons
  icon:

    # Repo Icon
    repo: fontawesome/brands/github

    # Tag Icons
    tag:
      swift: fontawesome/brands/swift
      python: fontawesome/brands/python
      python3: fontawesome/brands/python
      easy: fontawesome/brands/github
      medium: fontawesome/solid/dumpster
      hard: fontawesome/solid/dumpster-fire

  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  # Tags
  - tags:
      tags_file: tags.md

  # Social Cards
  - social:

  # Search Bar
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

  # Blog Posts: https://squidfunk.github.io/mkdocs-material/plugins/blog/#meta.date-custom-date    
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/articles"
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_excerpt: optional
      post_excerpt_max_authors: 2
      post_excerpt_max_categories: 2
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      post_readtime_words_per_minute: 300
      archive: false
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "archive/{date}"
      archive_toc: true
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      categories_slugify_separator: _
      categories_allowed:
        - Easy
        - Medium
        - Hard
        - Swift
        - Python
        - Python3
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      pagination_format: "~2~"
      pagination_if_single_page: false
      pagination_keep_content: false
      authors: true


# Additional configuration
extra:
  # Tag id: icon
  tags:
    Swift: swift
    Python: python
    Python3: python3
    Easy: easy
    Medium: medium
    Hard: hard

    # Cookies Message
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      
  # Versioning
  version:
    provider: mike

  # Hide Generator
  generator: false
  annotate:
    json: [.s2]

  # Social Icons
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tywysocki
    - icon: fontawesome/regular/gem
      link: https://leetcode.com/tywysocki


# Custom CSS
extra_css:
  - stylesheets/extra.css


# Custom JavaScript
extra_javascript:
  - javascripts/tablesort.js


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink:
      separator: "_"
  - footnotes
  - md_in_html
  - tables
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.html
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: tywysocki
      repo: leetcode-solutions
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - Home: 'index.md'
  - Featured: 'page2.md'
  - Solutions: 'solutions.md'
  - Categories: 'categories.md'
  - Tags: 'tags.md'
  - Blog: 'blog/index.md'
